steps:
# Build the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/thesistracker-448622/thesistracker/thesistracker:tag1', '.']
# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/thesistracker-448622/thesistracker/thesistracker:tag1']
# Deploy image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'thesistracker', '--image', 'us-central1-docker.pkg.dev/thesistracker-448622/thesistracker/thesistracker:tag1', '--region', 'us-central1']
images:
- 'us-central1-docker.pkg.dev/thesistracker-448622/thesistracker/thesistracker:tag1'