[project]
name = "thesistrackerdjango"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cffi>=1.17.1",
    "cryptography>=44.0.0",
    "django>=5.1.5",
    "django-allauth>=65.3.1",
    "django-extensions>=3.2.3",
    "google-api-python-client>=2.160.0",
    "gunicorn>=23.0.0",
    "plotly>=5.24.1",
    "pycparser>=2.22",
    "pyjwt==1.7.1",
    "pylatexenc>=2.10",
    "python-docx>=1.1.2",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "rsa>=4.9",
    "slackclient>=2.9.4",
    "urllib3>=2.3.0",
    "whitenoise>=6.9.0",
]
